project:
  type: website

website:
  title: "Skrub learning materials"
  favicon: "images/skrub.svg"
  navbar:
    left:
      # - href: index.qmd
      #   text: Home
      - href: slides/index_slides.qmd
        text: Slides
      - href: notebooks/index_notebooks.qmd
        text: Notebooks
      - href: https://skrub-data.org/stable/reference/index.html
        text: API docs
      - href: https://skrub-data.org/stable/auto_examples/index.html
        text: Examples


format:
  html:
    theme: united
    css: styles.css
    toc: true



